const {
  BACKUPS_MACHINES_ROOT,
  BACKUPS_ROOT,
  IMAGES_ROOT,
  TARGET_METADATA_ROOT,
  VIDEOS_ROOT,
  configPath,
  errorReportPath,
  hashPath,
  legacyHashRecordPath,
  machineBackupRoot,
  machinePath,
  mediaRoot,
  mergedBackupRoot,
  resolveTargetRoot,
  scanCurrentPath,
  sourcePath,
  targetMetadataRoot,
  tempRoot,
  toPosixPath
} = require('./paths');

module.exports = {
  BACKUPS_MACHINES_ROOT,
  BACKUPS_ROOT,
  IMAGES_ROOT,
  METADATA_ROOT: TARGET_METADATA_ROOT,
  VIDEOS_ROOT,
  configPath,
  errorReportPath,
  hashPath,
  legacyHashRecordPath,
  machineBackupRoot,
  machinePath,
  mediaRoot,
  mergedBackupRoot,
  metadataRoot: targetMetadataRoot,
  resolveTargetRoot,
  scanCurrentPath,
  sourcePath,
  tempRoot,
  toPosixPath
};
